<script setup>
import {ref} from 'vue'
import {useRouter} from 'vue-router'
import {Search,EditPen,Menu,Close,Bell,ArrowDown} from '@element-plus/icons-vue'
import {useAuthStore} from './stores/auth.js'
const router=useRouter(),auth=useAuthStore(),keyword=ref(''),mobileOpen=ref(false)
const search=()=>{if(keyword.value.trim())router.push({path:'/search',query:{keyword:keyword.value.trim()}})}
const goPublish=()=>router.push(auth.loggedIn?'/publish':'/login?redirect=/publish')
const logout=()=>{auth.logout();router.push('/')}
</script>
<template><div class="site-shell"><header class="site-header"><div class="nav-wrap"><router-link to="/" class="brand" @click="mobileOpen=false"><img src="/uploads/demo/logo.png" alt="山海迹"><span><b>山海迹</b><small>TRAVEL NOTES</small></span></router-link><nav :class="{open:mobileOpen}"><router-link to="/" @click="mobileOpen=false">首页</router-link><router-link to="/destinations" @click="mobileOpen=false">目的地</router-link><router-link to="/guides" @click="mobileOpen=false">旅行攻略</router-link><router-link to="/routes" @click="mobileOpen=false">行程路线</router-link><router-link to="/topics" @click="mobileOpen=false">旅行专题</router-link></nav><div class="nav-actions"><div class="nav-search"><el-icon><Search/></el-icon><input v-model="keyword" aria-label="搜索攻略、目的地或路线" placeholder="搜索灵感" @keyup.enter="search"></div><button class="publish-button" @click="goPublish"><el-icon><EditPen/></el-icon>写攻略</button><template v-if="auth.loggedIn"><router-link to="/user/messages" class="icon-button" aria-label="消息"><el-icon><Bell/></el-icon></router-link><el-dropdown><button class="user-button"><img :src="auth.user?.avatar||'/uploads/demo/avatars/avatar-004.png'" alt="用户头像"><span>{{auth.user?.nickname}}</span><el-icon><ArrowDown/></el-icon></button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="router.push('/user/profile')">个人中心</el-dropdown-item><el-dropdown-item @click="router.push('/user/guides')">我的攻略</el-dropdown-item><el-dropdown-item @click="router.push('/user/routes')">我的路线</el-dropdown-item><el-dropdown-item divided @click="logout">退出登录</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template><router-link v-else to="/login" class="login-link">登录</router-link><button class="mobile-toggle" aria-label="切换导航" @click="mobileOpen=!mobileOpen"><el-icon><Close v-if="mobileOpen"/><Menu v-else/></el-icon></button></div></div></header><main><router-view/></main><footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><div class="brand light"><img src="/uploads/demo/logo.png" alt="山海迹"><span><b>山海迹</b><small>TRAVEL NOTES</small></span></div><p>把远方写成可以出发的计划。认真分享每一段路，也尊重每一种旅行方式。</p></div><div><h4>发现旅行</h4><router-link to="/destinations">热门目的地</router-link><router-link to="/guides">精选攻略</router-link><router-link to="/routes">推荐路线</router-link></div><div><h4>关于平台</h4><a href="#">平台介绍</a><a href="#">内容规范</a><a href="#">使用帮助</a></div><div><h4>联系我们</h4><p>travel@example.com</p><p>毕业设计演示项目</p><p>服务时间 09:00–18:00</p></div></div><div class="footer-bottom"><span>© 2026 山海迹旅游攻略分享平台</span><span>本地原创演示素材 · 无外部图床依赖</span></div></footer></div></template>

